name: Check and Test Platform
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: prepare nix environment
        run: nix develop --command echo done!

      - name: build host
        run: nix develop --command zig build -Dtype=release

      - name: build site
        run: nix develop --command zig build -Dtype=site

      - name: run host tests
        run: nix develop --command zig build test

      - name: type-check platform code
        run: nix develop --command roc check platform/main.roc

      - name: run platform tests
        run: nix develop --command roc test platform/main.roc

      - name: test example code
        run: nix develop --command ./example/build.roc --linker=legacy prod /tmp/output
